"use client";

import { useMemo, useState } from "react";

export type ShowcaseEntry = {
  id: number;
  grade: number;
  skill: string;
  page: string;
  topic: string;
  status: "OK" | "ERROR";
  html_file: string;
  error?: string;
};

type Props = {
  tag: string;
  entries: ShowcaseEntry[];
  generatedAt: string | null;
  initialLpId: number | null;
};

export function ShowcaseTemplate({
  tag,
  entries,
  generatedAt,
  initialLpId,
}: Props) {
  const firstOk = entries.find((e) => e.status === "OK") ?? entries[0];
  const fallbackId = firstOk?.id ?? null;
  const seeded =
    initialLpId !== null && entries.some((e) => e.id === initialLpId)
      ? initialLpId
      : fallbackId;

  const [selectedId, setSelectedId] = useState<number | null>(seeded);
  const [iframeLoading, setIframeLoading] = useState(true);
  const [copyState, setCopyState] = useState<"idle" | "copied" | "failed">(
    "idle",
  );

  const grouped = useMemo(() => {
    const map = new Map<number, ShowcaseEntry[]>();
    for (const e of entries) {
      const arr = map.get(e.grade) ?? [];
      arr.push(e);
      map.set(e.grade, arr);
    }
    return Array.from(map.entries())
      .sort(([a], [b]) => a - b)
      .map(([grade, items]) => ({
        grade,
        items: items.sort((a, b) => a.id - b.id),
      }));
  }, [entries]);

  if (!entries.length) {
    return (
      <main className="min-h-screen bg-dars-parchment text-dars-ink flex items-center justify-center p-10">
        <div className="max-w-md text-center">
          <p className="font-serif text-2xl mb-3">Showcase is empty</p>
          <p className="text-sm text-dars-muted">
            No lesson plans have been generated yet for{" "}
            <code className="text-dars-terra">{tag}</code>.
          </p>
        </div>
      </main>
    );
  }

  const selected = entries.find((e) => e.id === selectedId) ?? entries[0];

  const handleSelect = (id: number) => {
    if (id === selectedId) return;
    setIframeLoading(true);
    setSelectedId(id);
    if (typeof window !== "undefined") {
      const url = new URL(window.location.href);
      url.searchParams.set("lp", String(id));
      window.history.replaceState({}, "", url.toString());
    }
  };

  const handleCopyLink = async () => {
    if (typeof window === "undefined") return;
    const url = new URL(window.location.href);
    url.searchParams.set("lp", String(selected.id));
    try {
      await navigator.clipboard.writeText(url.toString());
      setCopyState("copied");
    } catch {
      setCopyState("failed");
    }
    setTimeout(() => setCopyState("idle"), 1600);
  };

  const openHref = `/showcase/${tag}/${selected.html_file}`;
  const subtitle =
    "10 plans generated by Dars · Grade 2 & 5 · English · ICT curriculum";

  return (
    <main className="min-h-screen bg-dars-parchment text-dars-ink flex flex-col">
      <header className="border-b border-dars-rule-light px-6 py-6 bg-dars-parchment-mid">
        <div className="max-w-7xl mx-auto flex items-end justify-between gap-6 flex-wrap">
          <div className="max-w-2xl">
            <span className="block text-[11px] font-bold tracking-[2px] uppercase text-dars-terra">
              Lesson plan showcase
            </span>
            <h1 className="font-serif text-3xl sm:text-4xl mt-1 tracking-[-0.5px] leading-[1.1]">
              Sample lesson plans
            </h1>
            <p className="text-sm text-dars-muted mt-2 leading-relaxed">
              {subtitle}
            </p>
          </div>
          {generatedAt ? (
            <div className="text-right">
              <span className="block text-[10px] font-bold tracking-[1.5px] uppercase text-dars-muted">
                Generated
              </span>
              <span className="block text-xs text-dars-ink-soft mt-1">
                {generatedAt}
              </span>
            </div>
          ) : null}
        </div>
      </header>

      <div className="flex-1 grid grid-cols-1 lg:grid-cols-[340px_1fr] gap-0 max-w-7xl mx-auto w-full">
        <aside className="border-b lg:border-b-0 lg:border-r border-dars-rule-light bg-dars-parchment-mid">
          {grouped.map(({ grade, items }) => (
            <div key={grade}>
              <div className="px-5 py-2.5 bg-dars-parchment-deep border-b border-dars-rule-light flex items-baseline justify-between">
                <span className="text-[11px] font-bold tracking-[2px] uppercase text-dars-ink">
                  Grade {grade}
                </span>
                <span className="text-[10px] text-dars-muted">
                  {items.length} lesson plans
                </span>
              </div>
              <ul className="divide-y divide-dars-rule-light">
                {items.map((e) => {
                  const active = e.id === selected.id;
                  return (
                    <li key={e.id}>
                      <button
                        type="button"
                        onClick={() => handleSelect(e.id)}
                        className={
                          "w-full text-left px-5 py-4 transition-colors flex items-start gap-3 " +
                          (active
                            ? "bg-dars-parchment border-l-2 border-dars-terra"
                            : "hover:bg-dars-parchment border-l-2 border-transparent")
                        }
                      >
                        <span className="flex-1 min-w-0">
                          <span className="block text-sm font-semibold tracking-[-0.2px] text-dars-ink">
                            {e.skill}
                          </span>
                          <span className="block text-xs text-dars-muted mt-0.5">
                            {e.topic ? `${e.topic} · p. ${e.page}` : `p. ${e.page}`}
                          </span>
                          {e.status === "ERROR" && e.error ? (
                            <span className="block text-[11px] text-dars-terra mt-1 line-clamp-2">
                              {e.error}
                            </span>
                          ) : null}
                        </span>
                        <SkillIcon
                          skill={e.skill}
                          tone={active ? "active" : "muted"}
                        />
                      </button>
                    </li>
                  );
                })}
              </ul>
            </div>
          ))}
        </aside>

        <section className="bg-dars-parchment flex flex-col">
          <div className="px-6 py-3 border-b border-dars-rule-light flex items-center justify-between gap-4 flex-wrap">
            <div className="min-w-0">
              <div className="text-[11px] font-bold tracking-[2px] uppercase text-dars-muted">
                Grade {selected.grade} · {selected.skill}
              </div>
              <div className="font-serif text-lg tracking-[-0.2px] truncate">
                {selected.topic
                  ? `${selected.topic} — p. ${selected.page}`
                  : `Page ${selected.page}`}
              </div>
            </div>
            <div className="flex items-center gap-2">
              <a
                href={openHref}
                target="_blank"
                rel="noopener noreferrer"
                className="text-[11px] font-semibold tracking-[1px] uppercase text-dars-ink-soft hover:text-dars-terra border border-dars-rule-light hover:border-dars-terra px-3 py-1.5 rounded-md no-underline transition-colors"
              >
                Open in new tab
              </a>
              <a
                href={openHref}
                target="_blank"
                rel="noopener noreferrer"
                className="text-[11px] font-semibold tracking-[1px] uppercase text-dars-ink-soft hover:text-dars-terra border border-dars-rule-light hover:border-dars-terra px-3 py-1.5 rounded-md no-underline transition-colors"
                title="Open the standalone print-ready page"
              >
                Print
              </a>
              <button
                type="button"
                onClick={handleCopyLink}
                className="text-[11px] font-semibold tracking-[1px] uppercase text-dars-ink-soft hover:text-dars-terra border border-dars-rule-light hover:border-dars-terra px-3 py-1.5 rounded-md transition-colors"
              >
                {copyState === "copied"
                  ? "Link copied"
                  : copyState === "failed"
                    ? "Copy failed"
                    : "Copy share link"}
              </button>
            </div>
          </div>
          <div className="flex-1 min-h-[70vh] relative">
            {selected.status === "OK" ? (
              <>
                {iframeLoading ? <IframeSkeleton /> : null}
                <iframe
                  key={selected.id}
                  src={`/showcase/${tag}/${selected.html_file}`}
                  title={`Lesson plan ${selected.id}`}
                  onLoad={() => setIframeLoading(false)}
                  className="w-full h-full min-h-[70vh] border-0 bg-white"
                />
              </>
            ) : (
              <div className="p-10">
                <p className="font-serif text-xl mb-2">
                  This lesson plan failed to generate
                </p>
                <p className="text-sm text-dars-muted mb-4">
                  Grade {selected.grade}, {selected.skill}, page {selected.page}.
                </p>
                <pre className="bg-dars-parchment-mid border border-dars-rule-light rounded-md p-4 text-xs text-dars-ink whitespace-pre-wrap break-words max-w-2xl">
                  {selected.error ?? "Unknown error"}
                </pre>
              </div>
            )}
          </div>
        </section>
      </div>

      <footer className="border-t border-dars-rule-light px-6 py-4 bg-dars-parchment-mid">
        <div className="max-w-7xl mx-auto flex items-center justify-between text-[11px] tracking-[1.5px] uppercase text-dars-muted">
          <span>Generated by Dars</span>
          <span>drs.taleemabad.com</span>
        </div>
      </footer>
    </main>
  );
}

function IframeSkeleton() {
  return (
    <div
      aria-hidden="true"
      className="absolute inset-0 bg-dars-parchment animate-pulse pointer-events-none"
    >
      <div className="max-w-[720px] mx-auto pt-12 px-7 space-y-4">
        <div className="h-2 w-24 bg-dars-parchment-deep rounded" />
        <div className="h-8 w-2/3 bg-dars-parchment-deep rounded" />
        <div className="h-px w-full bg-dars-rule-light my-6" />
        <div className="h-3 w-32 bg-dars-parchment-deep rounded" />
        <div className="h-3 w-11/12 bg-dars-parchment-mid rounded" />
        <div className="h-3 w-10/12 bg-dars-parchment-mid rounded" />
        <div className="h-3 w-9/12 bg-dars-parchment-mid rounded" />
        <div className="h-3 w-32 bg-dars-parchment-deep rounded mt-8" />
        <div className="h-3 w-11/12 bg-dars-parchment-mid rounded" />
        <div className="h-3 w-10/12 bg-dars-parchment-mid rounded" />
      </div>
    </div>
  );
}

function SkillIcon({
  skill,
  tone,
}: {
  skill: string;
  tone: "active" | "muted";
}) {
  const stroke = tone === "active" ? "var(--color-dars-terra)" : "var(--color-dars-muted-light)";
  const common = {
    width: 22,
    height: 22,
    viewBox: "0 0 24 24",
    fill: "none",
    stroke,
    strokeWidth: 1.6,
    strokeLinecap: "round" as const,
    strokeLinejoin: "round" as const,
    "aria-hidden": true,
  };
  const s = skill.toLowerCase();
  if (s.startsWith("reading")) {
    return (
      <svg {...common}>
        <path d="M3 5h7a3 3 0 0 1 3 3v11" />
        <path d="M21 5h-7a3 3 0 0 0-3 3v11" />
        <path d="M3 5v14h7" />
        <path d="M21 5v14h-7" />
      </svg>
    );
  }
  if (s.startsWith("creative writing") || s.includes("writing")) {
    return (
      <svg {...common}>
        <path d="M14 4l6 6-9 9H5v-6z" />
        <path d="M13 5l6 6" />
      </svg>
    );
  }
  if (s.startsWith("comprehension q") || s.includes("q&a")) {
    return (
      <svg {...common}>
        <path d="M4 6h12" />
        <path d="M4 12h12" />
        <path d="M4 18h8" />
        <circle cx="20" cy="6" r="0.6" fill={stroke} />
        <circle cx="20" cy="12" r="0.6" fill={stroke} />
        <circle cx="20" cy="18" r="0.6" fill={stroke} />
      </svg>
    );
  }
  if (s.startsWith("grammar")) {
    return (
      <svg {...common}>
        <path d="M3 18l4-11 4 11" />
        <path d="M4.5 14h5" />
        <path d="M14 7v11" />
        <path d="M14 13a3 3 0 1 1 0-5h2v5z" />
      </svg>
    );
  }
  if (s.startsWith("comprehension w") || s.includes("meaning")) {
    return (
      <svg {...common}>
        <rect x="4" y="4" width="16" height="16" rx="2" />
        <path d="M8 8h8" />
        <path d="M8 12h8" />
        <path d="M8 16h5" />
      </svg>
    );
  }
  return (
    <svg {...common}>
      <circle cx="12" cy="12" r="8" />
    </svg>
  );
}
